apiVersion: v1
kind: Service
metadata:
  name: chaosops-app-svc
  namespace: chaosops
  labels:
    app: chaosops-app
spec:
  type: NodePort
  selector:
    app: chaosops-app
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080 # matches terraform var.app_node_port; must stay in the 30000-32767 SG range
